apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-service-config
data:
  AWS_REGION: "us-east-1"

  KAFKA_BOOTSTRAP_SERVERS: "b-1.msk-cluster.amazonaws.com:9098,b-2.msk-cluster.amazonaws.com:9098"

  PROCESSED_TRANSACTIONS_TABLE: "processed-transactions"
  TRANSACTION_SUMMARY_TABLE: "transaction-summary"

  KAFKA_TOPIC: "transactions.processed"

  ERROR_THRESHOLD: "15"
  CIRCUIT_ENABLED: "true"
  RETRY_MAX_ATTEMPTS: "3"

  # Logging configuration
  LOGGING_PATTERN_CONSOLE: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","thread":"%t","logger":"%c","message":"%m"}%n'